-- =============================================================================
-- RCCP One — SUPERSEDED SCRIPT
--
-- This script has been replaced by:
--   06_resource_requirements.sql
--
-- The support_staff_pools and support_staff_line_assignments tables have been
-- removed from the design. The unified resource requirements model in
-- 06_resource_requirements.sql covers all staff roles (both line-level and
-- plant-level shared roles) in a single, Excel-uploadable structure.
--
-- Do NOT run this script. It is kept for reference only.
-- =============================================================================
